Repository BlackToppStudios/Mezz_StaticFoundation, pull requests merged in 2019-09, with the labels that each got.

#67 Feature-NewTypes
  include/DataTypes.h
Labels: enhancement

#68 Bug-MSVCOptional
  include/DataTypes.h
Labels: bug

#69 Proposed fix comment nits
  .travis.yml
  include/DataTypes.h
  include/DetectionTraits.h
Labels: perfective
